apiVersion: v1 
kind: PersistentVolume
metadata:
  name: efs-static
spec:
  capacity:
  storage: 5Gi
volumeMode: Filesystem
accessModes:
 - ReadWriteOnce
storageClassName: "" # This should be empty in static provisioning
persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0587a89d2765af7b8