apiVersion: v1
kind: Pod 
metadata:
    name: multicontainer
    labels:
      project: roboshop
      purpose: multicontainer
spec:
  containers:
  - name: nginx
    image: nginx
  - name: busybox
    image: busybox
    command: ["sleep", "3600"]