apiVersion: v1
kind: Pod
metadata:
  name: labels
  labels:
    project: roboshop
    environment: development
    component: sql
    tier: backend
spec:
  containers:
  - name: nginx
    image: nginx
